language: node_js
node_js:
  - '10'

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn

script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  local_dir: build
  on:
    branch: master
